---
abstract: 'Introspect a database and dynamically generate models'
author:
  - 'James Laver <james.laver@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  Test::More: '0.89'
  Test::Most: '0'
  perl: '5.006'
configure_requires:
  ExtUtils::MakeMaker: '0'
  perl: '5.006'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.037, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: BeastForm
provides:
  BeastForm:
    file: lib/BeastForm.pm
    version: '0.000001'
  BeastForm::Awesome:
    file: lib/_attic/Awesome.pm
    version: '0.000001'
  BeastForm::Col:
    file: lib/_attic/Col.pm
    version: '0.000001'
  BeastForm::Constraint::Check:
    file: lib/BeastForm/Check.pm
    version: '0.000001'
  BeastForm::DB:
    file: lib/BeastForm/DB.pm
    version: '0.000001'
  BeastForm::DBIL::Table:
    file: lib/_attic/DBIL/Table.pm
    version: '0.000001'
  BeastForm::Driver:
    file: lib/BeastForm/Driver.pm
    version: '0.000001'
  BeastForm::FK:
    file: lib/BeastForm/FK.pm
    version: '0.000001'
  BeastForm::Field:
    file: lib/BeastForm/Field.pm
    version: '0.000001'
  BeastForm::Fieldset:
    file: lib/BeastForm/Fieldset.pm
    version: '0.000001'
  BeastForm::Key:
    file: lib/BeastForm/Key.pm
    version: '0.000001'
  BeastForm::Proc:
    file: lib/BeastForm/Proc.pm
    version: '0.000001'
  BeastForm::Reader::SQLT:
    file: lib/BeastForm/Reader/SQLT.pm
    version: '0.000001'
  BeastForm::Reader::SQLT::Constraint:
    file: lib/BeastForm/Reader/SQLT/Constraint.pm
    version: '0.000001'
  BeastForm::Reader::SQLT::Field:
    file: lib/BeastForm/Reader/SQLT/Field.pm
    version: '0.000001'
  BeastForm::Reader::SQLT::Index:
    file: lib/BeastForm/Reader/SQLT/Index.pm
    version: '0.000001'
  BeastForm::Reader::SQLT::Proc:
    file: lib/BeastForm/Reader/SQLT/Proc.pm
    version: '0.000001'
  BeastForm::Reader::SQLT::Schema:
    file: lib/BeastForm/Reader/SQLT/Schema.pm
    version: '0.000001'
  BeastForm::Reader::SQLT::Table:
    file: lib/BeastForm/Reader/SQLT/Table.pm
    version: '0.000001'
  BeastForm::Reader::SQLT::Trigger:
    file: lib/BeastForm/Reader/SQLT/Trigger.pm
    version: '0.000001'
  BeastForm::Reader::SQLT::View:
    file: lib/BeastForm/Reader/SQLT/View.pm
    version: '0.000001'
  BeastForm::Role::Awesome:
    file: lib/BeastForm/Role/Awesome.pm
    version: '0.000001'
  BeastForm::Role::Connected:
    file: lib/BeastForm/Role/Connected.pm
    version: '0.000001'
  BeastForm::Role::Constraint:
    file: lib/BeastForm/Role/Constraint.pm
    version: '0.000001'
  BeastForm::Role::DBIL:
    file: lib/BeastForm/Role/DBIL.pm
    version: '0.000001'
  BeastForm::Role::Introspective:
    file: lib/BeastForm/Role/Introspective.pm
    version: '0.000001'
  BeastForm::Role::Process:
    file: lib/BeastForm/Role/Process.pm
    version: '0.000001'
  BeastForm::Schema:
    file: lib/BeastForm/Schema.pm
    version: '0.000001'
  BeastForm::Table:
    file: lib/BeastForm/Table.pm
    version: '0.000001'
  BeastForm::Trigger:
    file: lib/BeastForm/Trigger.pm
    version: '0.000001'
  BeastForm::Util:
    file: lib/BeastForm/Util.pm
    version: '0.000001'
  BeastForm::View:
    file: lib/BeastForm/View.pm
    version: '0.000001'
  BeastForm::Writer::DBIL::Dynamic::Schema:
    file: lib/BeastForm/Writer/DBIL/Dynamic/Schema.pm
    version: '0.000001'
  BeastForm::Writer::DBIL::Dynamic::Table:
    file: lib/BeastForm/Writer/DBIL/Dynamic/Table.pm
    version: '0.000001'
recommends:
  Moo: '1.000008'
requires:
  BeastForm::Constraint: '0'
  BeastForm::DBIL::Builder::Dynamic: '0'
  BeastForm::DBIL::Schema: '0'
  BeastForm::Role::Writer::Schema: '0'
  BeastForm::Role::Writer::Table: '0'
  Carp: '0'
  DBI: '0'
  DBIx::Connector: '0'
  DBIx::Lite: '0'
  DBIx::Lite::Schema: '0'
  Data::Dumper: '0'
  Exporter: '0'
  Hash::Ordered: '0'
  List::Util: '0'
  Moo: '0'
  Moo::Role: '0'
  Package::Variant: '0'
  SQL::Translator: '0'
  parent: '0'
  perl: '5.006'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/kentnl/DBIx-BeastForm/issues
  homepage: https://github.com/kentnl/DBIx-BeastForm
  repository: https://github.com/kentnl/DBIx-BeastForm.git
version: '0.000001'
